source "http://rubygems.org"

gem "plek"
gem "rake"
gem "cucumber"
gem "webrat"
gem "mechanize"
gem "rspec"
gem "rest-client"
gem "mysql2"
gem "stomp"
gem "mongo"
gem 'WAAT', git: "git@github.com:robyoung/WAAT-ruby.git"
